#########################################################################
# StatisticsUI by bj4rne - Configuration file
# https://github.com/bj4rnee/StatisticsUI
# Please check for updates, and remember to update the config if needed!
#########################################################################

# Section related to the use of a permission system.

permission-system:
  
# Set this to 'true' if you want to enable the permission system.
# This is turned off by default.
  
enabled: false